### ISSUE TITLE
Organization clean-up notification

### ISSUE THREAD

**Issue by roopchansinghv** [nih-fmrif/notifyOrganization#1]
@nih-fmrif/everyone 

The owners of the NIH-FMRIF organization on GitHub will be cleaning up our repositories and organization.

All teams without repositories will be removed, and all current members outside of the actual FMRIF group will also be removed.  If there are repositories we have shared and you still need access to, please let us know, and we will convert you to collaborators to allow continued access.

Thanks
Vinai

**Comment by krishusc** [comment]
Hi Vinai,

Souheil just gave me access to the ge-tools, so that we could do the P-File to ISMRMRD conversion.

May I continue to have access just to that, after the reorganization?

Krishna
